### PR TITLE
Rudimentary Javascript Topic TBD

### PR DESCRIPTION
**Pull request by robdrimmie**
I'd like to be a speaker, this is not a time-sensitive request.

As a starting point I am thinking about the differences between `var` and `let` and `const` in es2015. A mix of why bother, how to pick and some practical examples.

I'm not bound to this specific case, the general idea behind what I'm aiming for is content that newcomers to the language can understand, explained as deeply as possible in the time available. Exposure to thinking about language internals.

### CODE REVIEW

**Comment by gtanner** [comment]
So are you thinking:

"All the cool ES2015 highlights I can talk about in 10 minutes?"

**Comment by robdrimmie** [comment]
no, more like "10 minutes on these three keywords and that's it."

**Comment by gtanner** [comment]
I actually really like this :)  are you up for speaking this month?

**Comment by robdrimmie** [comment]
Probably! I need to confirm that I can come. Our stupid dog just got knee surgery (like, she literally got home from the vets 20 minutes ago) and I'm not sure how that affects scheduling/availability. I'm 90% likely as of right now though.

edit: I can confirm availability tomorrow

**Comment by robdrimmie** [comment]
I am available! If there is still a spot, I will happily speak.

**Comment by gtanner** [comment]
Sounds good :) you're in

**Pull request closed without merging**
