### PR TITLE
Chris Silivestru wants to be a speaker.

### PR DESCRIPTION
**Pull request by CSilivestru**
I'm not entirely sure what I want to talk about yet but I have ideas brewing...

I've noticed that JS is improving itself in the form of making the language itself more 'perfect' through ES6+ with many more linting and transpiling alternatives. I'm calling that (at least for right now...) the right-quadrant of JS. The left-quadrant are the fundamentals of the language that get no real press or air-time. Why is this important? Because I don't think JS will become the next major language (think the next Java) because of its linting. I think it will turn into that because it's what kids will learn in grade school. I'd like to do a talk centered around why this is a good idea.

I just came up with this concept now and I'm not married to it so feedback is appreciated but I feel like I can make a compelling 10 minute talk about it :-).

### CODE REVIEW

**Comment by carlosperez** [comment]
I am Carlos, and I approve of this talk. Of course, I have no merge rights @gtanner ... thanks. I'm just the "designer". ;)

**Comment by gtanner** [comment]
I do like where this is going :)  My main concern is making this the "bitHound" show.

Let me put this on the "maybe" list for a day or so while I drum up some more talk opportunities.  I do want this talk for sure because it sounds awesome, might be good to put it in next month if I do get some other people interested in talking though.

**Comment by CSilivestru** [comment]
Sounds good -- totally understand :-D

**Comment by gtanner** [comment]
You know what, this is more of the Vidyard, Mozzaz, Dozr, Practical Blend show now ;) I vote lets go with it.  Do you think you can think of a cool title?

**Comment by CSilivestru** [comment]
Yeah I'll think of something and commit it when I do :-). As well as a short description. 
Thanks!

**Comment by CSilivestru** [comment]
@gtanner Title has been added. I realized there isn't actually a spot on the page for a description so I just decided to leave that out. Please let me know if you need anything else!

**Pull request merged**
